services:
  yaqizhou:
    image: ${DOCKER_REGISTRY-}yaqizhou
    build:
      context: .
      dockerfile: YaqiZhou/Dockerfile
    depends_on:
      - "mssql"
  
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "sqlYaqi"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd5678@
    restart: always
